# Generated by Django 4.2.6 on 2023-10-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
